version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/with-cache:
          steps:
            - run: npm test
            - run: npx codecov
workflows:
    test:
      jobs:
        - test
