version: 2.1
orbs:
  node: circleci/node@2.0.3
  browser-tools: circleci/browser-tools@1.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run: npx codecov
workflows:
    test:
      jobs:
        - test
